name: CI Workflow
on:
    workflow_dispatch:

jobs:
    CI-Pipeline:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v7
            
            - name: Setup Python
              uses: actions/setup-python@v7
              with:
                python-version: '3.12'
                cache: pip
            
            - name: install Dependancies
              run: |
                pip install -r requirements.txt -r requirements-dev.txt
             
            - name: Cache
              uses: actions/cache@v4                      

            
            - name: run linter
              run: |
                flake8 . --count --show-source --statistics
            
            - name: Run test
              run: |
                pytest --cov=app --cov-report=term-missing
            
            - name: Failure step
              if: failure()
              run: exit 1



