on:
    workflow_run:
        workflows: [ "Run Tests" ]
        types: [completed]

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Precheck
              run: |
                echo "Precheck Passed"