name: Environment Workflow
on:
    workflow_dispatch:
env:
    APP_NAME: myapp 

jobs:
    workflowlevel:
        runs-on: ubuntu-latest
        steps:
            - name: print workflow env variable
              run: echo "Workflow env variable:${{ env.APP_NAME }}"

    joblevelenv:
        env: 
            ENVIRONMENT: staging
        runs-on: ubuntu-latest
        steps:
            - name: Print Job level env variable
              run: echo "Job level env variable:${{ env.ENVIRONMENT }}"

    steplevelenv:
        env:
            ENVIRONMENT: staging
        runs-on: ubuntu-latest
        steps:
            - name: print all step level env and all other env variables
              run: |
                echo "Step level env:$VERSION"
                echo "Job Level Env: $ENVIRONMENT"
                echo "Workflowlevel Env: $APP_NAME "
                echo "Commit SHA ${{ github.sha}}"
                echo "Actor ${{ github.actor }}"
              env: 
                VERSION: 1.0.0
                
            
