name: Environment Workflow
on:
    workflow_dispatch:
env:
    APP_NAME: myapp 

jobs:
    workflowlevel:
        runs-on: ubuntu-latest
        steps:
            - name: print workflow env variable
              run: echo "Workflow env variable:${{ env.APP_NAME }}"

    joblevelenv:
        env: 
            ENVIRONMENT: staging
        runs-on: ubuntu-latest
        steps:
            - name: Print Job level env variable
              run: echo "Job level env variable:${{ env.ENVIRONMENT }}"