name: GitHub Hosted Runner
on:
    push:
        branches:
            - main
jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: System Info
              run: |
                echo "OS Name:${{ runner.os }}"
                echo "Hostame: $(hostname)"
                echo "Current User: $(whoami)"

            - name: Pre-installed Tools
              run: |
                echo "Python Version: $(python --version)"
                echo "Docker Version: $(docker --version)"
                echo "Node Version: $(node --version)"
                echo "Git Version: $(git --version)"

    windows:
        runs-on: windows-latest
        steps:
            - name: System Info
              run: |
                echo "OS Name:${{runner.os}}"
                echo "Hostame: $(hostname)"
                echo "Current User: $(whoami)"
            - name: Pre-installed Tools
              run: |
                echo "Python Version: $(python --version)"
                echo "Docker Version: $(docker --version)"
                echo "Node Version: $(node --version)"
                echo "Git Version: $(git --version)"
                
    macos:
        runs-on: macos-latest
        steps:
            - name: System Info
              run: |
                echo "OS Name:${{runner.os}}"
                echo "Hostame: $(hostname)"
                echo "Current User: $(whoami)"
            - name: Pre-installed Tools
              run: |
                echo "Python Version: $(python --version)"
                echo "Docker Version: $(docker --version)"
                echo "Node Version: $(node --version)"
                echo "Git Version: $(git --version)"                
                