name: GitHub Hosted Runner
on:
    push:
        branches:
            - main
jobs:
    ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: System Info
              run: |
                echo "OS Name:${{ runner.os }}"
                echo "Hostame: $(hostname)"
                echo "Current User: $(whoami)"

    windows:
        runs-on: windows-latest
        steps:
            - name: System Info
              run: |
                echo "OS Name:${{runner.os}}"
                echo "Hostame: $(hostname)"
                echo "Current User: $(whoami)"
                
    macos:
        runs-on: macos-latest
        steps:
            - name: System Info
              run: |
                echo "OS Name:${{runner.os}}"
                echo "Hostame: $(hostname)"
                echo "Current User: $(whoami)"                
                