name: Hello
on:
  push:
    branches: 
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: greet
        run: echo "Hello From GitHub Actions!"

      - name: date and time
        run: date

      - name: Name of the branch
        run: echo ${{ github.ref_name }}

      - name: List files in repo
        run: ls -ltr 

      - name: Runners OS 
        run: echo ${{ runner.os}}