on:
    workflow_dispatch:

jobs:
    get-date:
        runs-on: ubuntu-latest
        outputs:
            date: ${{ steps.date.outputs.date }}
        steps:
            - name: set date as an output
              id: date
              run: |
                echo "date=$(date)" >> $GITHUB_OUTPUT

    print-date:
        needs: get-date
        runs-on: ubuntu-latest
        steps:
            - name: print date
              run: |
                echo "Date from get date job is ${{ needs.get-date.outputs.date }}"