name: Matix Workflow
on:
  push:
    branches:
      - main
jobs:
  matrix-strategy:
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest]
        exclude: 
          - python_version: "3.10"
          - os: windows-latest
      fail-fast: false



    runs-on: ${{matrix.os}}
    steps: 
      - name: Install python
        uses: actions/setup-python@v7
        with:
          python-version: ${{matrix.python_version}}
      - name: print version of python
        run: python --version

      - name: Fail conditon
        shell: bash
        run: |
          if [ "${{matrix.python_version}}" = "3.12" ]; then
          exit 1
          fi
