name: PR-Pipeline
on:
    pull_request:
        branches:
            - main
        types:
            - opened
            - synchronize

jobs:
    calltest:
        uses: ./.github/workflows/reusable-build-test.yml
        with:
            python_version: 3.12
            run_test: true
    pr-comment:
        runs-on: ubuntu-latest
        needs: calltest
        steps:
            - name: Check dependencies for Vulnerabilities
              uses: actions/dependency-review-action@v4
              with:
                fail-on-severity: critical

            - name: Summary
              run: |
                echo "PR Checks passsed for branch: ${{ github.base_ref }}"
