name: reusable workflow
on:
    workflow_call:
      inputs:
        app_name:
            required: true
            type: string
        environment:
            type: string
            required: true
            default: staging
      secrets:
        docker-token:
            required: true
      outputs:
        build_version: 
            value: ${{ jobs.buildv-generate.outputs.build_version }}
jobs:
    callworkflow:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6

            - name: print 
              run:
                echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"
            
            
            - name: docker token
              run: |
                if [ -z ${{ secrets.docker-token }} ];then
                  echo "Docker token is not set"
                else
                  echo "Docker token is set: true"
                fi
    buildv-generate:
        runs-on: ubuntu-latest
        outputs: 
            build_version: ${{ steps.build_version.outputs.Build_version }}
        steps:        
          - name: generate build version
            id: build_version
            run: |
                Build_version="v1.0-${{github.sha}}""
                "echo Build_version=$(Build_version)" >> $GITHUB_OUTPUT
              

