name: reusable workflow
on:
    workflow_call:
      inputs:
        app_name:
            required: true
            type: string
        environment:
            type: string
            required: true
            default: staging
      secrets:
        docker-token:
            required: true
jobs:
    callworkflow:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6

            - name: print 
              run:
                echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"
            
            
            - name: docker token
              run: |
                if [ -z ${{ secrets.docker-token }} ];then
                  echo "Docker token is not set"
                else
                  echo "Docker token is set: true"
                fi

