name: Reusable Workflow
on:
    workflow_call:
        inputs:
            app_name:
                type: string
                required: true
            environment:
                type: string
                required: true
                default: staging
        secrets:
            docker_token:
                required: true
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: print info
              run: |
                echo "Build ${{inputs.app_name}} for ${{ inputs.environment }}"
            
            - name: Check for docker token
              run: |
                if [ -z ${{ secrets.docker_token}} ]; then
                  echo "Docker token is set: False"
                else
                  echo "Docker token is set: True"
                fi
            
