name: Smart Triggers
on:
    push:
        branches:
            - main
            - release/*
        paths:
            - 'src/**'
            - 'app/**'


jobs:
    smartpipline:
        runs-on: ubuntu-latest
        steps:
            - name: Print
              run: |
                echo "Hello , this step is executed since its a valid push"